# docker-compose.yml
version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000" # Pastikan mapping-nya ke 5000
    env_file:
      - .env
    networks:
      - shared-net

# Tambahkan network
networks:
  shared-net:
    external: true # kita akan buat ini secara manual
