version: "3.8"

services:
  web:
    build: .
    container_name: tsi-document-share
    network_mode: "host" # This gives the container access to the host's network
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=mysql://root:admin@194.195.92.47:3309/document-share-tsi
      - NEXTAUTH_URL=http://localhost:5000
      - NEXTAUTH_SECRET=verySecretKey
    restart: unless-stopped
