# docker-compose.yml
version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000" # Pastikan mapping-nya ke 5000
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://root:admin@194.195.92.47:3309/document-share-tsi
      - NEXTAUTH_URL=http://localhost:5000
      - NEXTAUTH_SECRET=verySecretKey
    networks:
      - shared-net

# Tambahkan network
networks:
  shared-net:
    external: true # kita akan buat ini secara manual
