version: "3.8"

services:
  db:
    image: mysql:8
    restart: always
    container_name: mysql_tsi
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: document-share-tsi
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: nextjs_tsi
    ports:
      - "5000:3000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
