# docker-compose.yml
version: "3.8"

services:
  web:
    build: .
    container_name: nextjs_tsi
    ports:
      - "5000:3000"
    env_file:
      - .env
    # Hubungkan ke network yang sama dengan MySQL existing
    networks:
      - shared-net

# Tambahkan network
networks:
  shared-net:
    external: true # kita akan buat ini secara manual
